# permissions for end users to edit echoservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: echoserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: echo-server
    app.kubernetes.io/part-of: echo-server
    app.kubernetes.io/managed-by: kustomize
  name: echoserver-editor-role
rules:
- apiGroups:
  - servers.pwhitehead00.io
  resources:
  - echoservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servers.pwhitehead00.io
  resources:
  - echoservers/status
  verbs:
  - get
